<?php

namespace ContainerRhML9xs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZvEUv74Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZvEUv74' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZvEUv74'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'salleRepository' => ['privates', 'App\\Repository\\SalleRepository', 'getSalleRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'salleRepository' => 'App\\Repository\\SalleRepository',
            'slugger' => '?',
        ]);
    }
}
