<?php

namespace ContainerP00u8QY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OX5edVIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oX5edVI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oX5edVI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LPRepository' => ['privates', 'App\\Repository\\LignePanierRepository', 'getLignePanierRepositoryService', true],
            'produit' => ['privates', '.errored..service_locator.oX5edVI.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.oX5edVI": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'LPRepository' => 'App\\Repository\\LignePanierRepository',
            'produit' => 'App\\Entity\\Produit',
            'repo' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
