<?php

namespace ContainerP00u8QY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QjXv4JrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qjXv4Jr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qjXv4Jr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LPRepository' => ['privates', 'App\\Repository\\LignePanierRepository', 'getLignePanierRepositoryService', true],
        ], [
            'LPRepository' => 'App\\Repository\\LignePanierRepository',
        ]);
    }
}
