<?php

namespace ContainerP00u8QY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dvDt_OP.App\Entity\Panier' shared service.
     *
     * @return \App\Entity\Panier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dvDt_OP": it needs an instance of "App\\Entity\\Panier" but this type has been excluded in "config/services.yaml".');
    }
}
