<?php

namespace ContainerN1VLvIX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WpwJMw2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wpwJMw2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wpwJMw2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activite' => ['privates', '.errored..service_locator.wpwJMw2.App\\Entity\\Activite', NULL, 'Cannot autowire service ".service_locator.wpwJMw2": it needs an instance of "App\\Entity\\Activite" but this type has been excluded in "config/services.yaml".'],
            'activiteRepository' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'activite' => 'App\\Entity\\Activite',
            'activiteRepository' => 'App\\Repository\\ActiviteRepository',
            'slugger' => '?',
        ]);
    }
}
