<?php

namespace ContainerJQ7apOT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0EXxDU3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0EXxDU3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0EXxDU3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendrier' => ['privates', '.errored..service_locator.0EXxDU3.App\\Entity\\Calendrier', NULL, 'Cannot autowire service ".service_locator.0EXxDU3": it needs an instance of "App\\Entity\\Calendrier" but this type has been excluded in "config/services.yaml".'],
            'calendrierRepository' => ['privates', 'App\\Repository\\CalendrierRepository', 'getCalendrierRepositoryService', true],
        ], [
            'calendrier' => 'App\\Entity\\Calendrier',
            'calendrierRepository' => 'App\\Repository\\CalendrierRepository',
        ]);
    }
}
