<?php

namespace ContainerJQ7apOT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivite2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wpwJMw2.App\Entity\Activite' shared service.
     *
     * @return \App\Entity\Activite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wpwJMw2": it needs an instance of "App\\Entity\\Activite" but this type has been excluded in "config/services.yaml".');
    }
}
