<?php

namespace ContainerH5ZJt7G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SuP15tDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.suP15tD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.suP15tD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendar' => ['privates', '.errored..service_locator.suP15tD.App\\Entity\\Calendrier', NULL, 'Cannot autowire service ".service_locator.suP15tD": it needs an instance of "App\\Entity\\Calendrier" but this type has been excluded in "config/services.yaml".'],
            'mg' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'calendar' => 'App\\Entity\\Calendrier',
            'mg' => '?',
        ]);
    }
}
