<?php

namespace ContainerGx3VVsc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Evt9KOKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Evt9KOK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Evt9KOK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Normalizer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', true],
            'mr' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'Normalizer' => '?',
            'mr' => '?',
        ]);
    }
}
