<?php

namespace ContainerGx3VVsc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kjp190AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kjp190A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kjp190A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'map' => ['privates', '.errored..service_locator.Kjp190A.App\\Entity\\Map', NULL, 'Cannot autowire service ".service_locator.Kjp190A": it needs an instance of "App\\Entity\\Map" but this type has been excluded in "config/services.yaml".'],
            'mapRepository' => ['privates', 'App\\Repository\\MapRepository', 'getMapRepositoryService', true],
        ], [
            'map' => 'App\\Entity\\Map',
            'mapRepository' => 'App\\Repository\\MapRepository',
        ]);
    }
}
