<?php

namespace ContainerGx3VVsc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I9EJ4YGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I9EJ4YG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I9EJ4YG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activiteRepository' => ['privates', 'App\\Repository\\TestRepository', 'getTestRepositoryService', true],
        ], [
            'activiteRepository' => 'App\\Repository\\TestRepository',
        ]);
    }
}
