<?php

namespace ContainerGx3VVsc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IRuNtE2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iRuNtE2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iRuNtE2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'map' => ['privates', '.errored..service_locator.iRuNtE2.App\\Entity\\Map', NULL, 'Cannot autowire service ".service_locator.iRuNtE2": it needs an instance of "App\\Entity\\Map" but this type has been excluded in "config/services.yaml".'],
        ], [
            'map' => 'App\\Entity\\Map',
        ]);
    }
}
