<?php

namespace ContainerGx3VVsc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMap2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iRuNtE2.App\Entity\Map' shared service.
     *
     * @return \App\Entity\Map
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iRuNtE2": it needs an instance of "App\\Entity\\Map" but this type has been excluded in "config/services.yaml".');
    }
}
