<?php

namespace ContainerWNbIjNq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__FYv2LCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..fYv2LC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..fYv2LC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'MapRepository' => ['privates', 'App\\Repository\\MapRepository', 'getMapRepositoryService', true],
            'SalleRe' => ['privates', 'App\\Repository\\SalleRepository', 'getSalleRepositoryService', true],
        ], [
            'MapRepository' => 'App\\Repository\\MapRepository',
            'SalleRe' => 'App\\Repository\\SalleRepository',
        ]);
    }
}
