<?php

namespace ContainerWNbIjNq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VfSgjHfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VfSgjHf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VfSgjHf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\SalleRepository', 'getSalleRepositoryService', true],
            'serializer' => ['privates', 'messenger.transport.native_php_serializer', 'getMessenger_Transport_NativePhpSerializerService', true],
        ], [
            'repo' => 'App\\Repository\\SalleRepository',
            'serializer' => '?',
        ]);
    }
}
