<?php

namespace ContainerWNbIjNq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E0DYH7sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E0DYH7s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E0DYH7s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activite' => ['privates', '.errored..service_locator.E0DYH7s.App\\Entity\\Test', NULL, 'Cannot autowire service ".service_locator.E0DYH7s": it needs an instance of "App\\Entity\\Test" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'activite' => 'App\\Entity\\Test',
            'entityManager' => '?',
        ]);
    }
}
