<?php

namespace ContainerWNbIjNq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PylYTpQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PylYTpQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PylYTpQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'MapRepository' => ['privates', 'App\\Repository\\MapRepository', 'getMapRepositoryService', true],
            'salle' => ['privates', '.errored..service_locator.PylYTpQ.App\\Entity\\Salle', NULL, 'Cannot autowire service ".service_locator.PylYTpQ": it needs an instance of "App\\Entity\\Salle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'MapRepository' => 'App\\Repository\\MapRepository',
            'salle' => 'App\\Entity\\Salle',
        ]);
    }
}
