<?php

namespace ContainerWNbIjNq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IRNJR8u.App\Entity\Salle' shared service.
     *
     * @return \App\Entity\Salle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IRNJR8u": it needs an instance of "App\\Entity\\Salle" but this type has been excluded in "config/services.yaml".');
    }
}
