<?php

namespace ContainerPmRUC0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BkPMaRrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bkPMaRr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bkPMaRr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.oX5edVI', 'get_ServiceLocator_OX5edVIService', true],
            'App\\Controller\\CartController::addPanier' => ['privates', '.service_locator.5H3AoFL', 'get_ServiceLocator_5H3AoFLService', true],
            'App\\Controller\\CartController::delete' => ['privates', '.service_locator.nF0lhwc', 'get_ServiceLocator_NF0lhwcService', true],
            'App\\Controller\\CartController::deleteAll' => ['privates', '.service_locator.qjXv4Jr', 'get_ServiceLocator_QjXv4JrService', true],
            'App\\Controller\\CartController::deletePanier' => ['privates', '.service_locator.8hRU1F1', 'get_ServiceLocator_8hRU1F1Service', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.EJLorm2', 'get_ServiceLocator_EJLorm2Service', true],
            'App\\Controller\\CartController::panierShow' => ['privates', '.service_locator.1LTs2rq', 'get_ServiceLocator_1LTs2rqService', true],
            'App\\Controller\\CartController::remove' => ['privates', '.service_locator.nF0lhwc', 'get_ServiceLocator_NF0lhwcService', true],
            'App\\Controller\\CartController::test' => ['privates', '.service_locator.qjXv4Jr', 'get_ServiceLocator_QjXv4JrService', true],
            'App\\Controller\\CartController::update' => ['privates', '.service_locator.oX5edVI', 'get_ServiceLocator_OX5edVIService', true],
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.iPTmcBs', 'get_ServiceLocator_IPTmcBsService', true],
            'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.iPTmcBs', 'get_ServiceLocator_IPTmcBsService', true],
            'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController::new' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\ProduitController::AffichageBack' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController::AffichageFront' => ['privates', '.service_locator.epy_BmF', 'get_ServiceLocator_EpyBmFService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.KQfLtfZ', 'get_ServiceLocator_KQfLtfZService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.KQfLtfZ', 'get_ServiceLocator_KQfLtfZService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator._eIqBF_', 'get_ServiceLocator_EIqBFService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.oX5edVI', 'get_ServiceLocator_OX5edVIService', true],
            'App\\Controller\\CartController:addPanier' => ['privates', '.service_locator.5H3AoFL', 'get_ServiceLocator_5H3AoFLService', true],
            'App\\Controller\\CartController:delete' => ['privates', '.service_locator.nF0lhwc', 'get_ServiceLocator_NF0lhwcService', true],
            'App\\Controller\\CartController:deleteAll' => ['privates', '.service_locator.qjXv4Jr', 'get_ServiceLocator_QjXv4JrService', true],
            'App\\Controller\\CartController:deletePanier' => ['privates', '.service_locator.8hRU1F1', 'get_ServiceLocator_8hRU1F1Service', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.EJLorm2', 'get_ServiceLocator_EJLorm2Service', true],
            'App\\Controller\\CartController:panierShow' => ['privates', '.service_locator.1LTs2rq', 'get_ServiceLocator_1LTs2rqService', true],
            'App\\Controller\\CartController:remove' => ['privates', '.service_locator.nF0lhwc', 'get_ServiceLocator_NF0lhwcService', true],
            'App\\Controller\\CartController:test' => ['privates', '.service_locator.qjXv4Jr', 'get_ServiceLocator_QjXv4JrService', true],
            'App\\Controller\\CartController:update' => ['privates', '.service_locator.oX5edVI', 'get_ServiceLocator_OX5edVIService', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.iPTmcBs', 'get_ServiceLocator_IPTmcBsService', true],
            'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.iPTmcBs', 'get_ServiceLocator_IPTmcBsService', true],
            'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController:new' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\ProduitController:AffichageBack' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController:AffichageFront' => ['privates', '.service_locator.epy_BmF', 'get_ServiceLocator_EpyBmFService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.KQfLtfZ', 'get_ServiceLocator_KQfLtfZService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.KQfLtfZ', 'get_ServiceLocator_KQfLtfZService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator._eIqBF_', 'get_ServiceLocator_EIqBFService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::addPanier' => '?',
            'App\\Controller\\CartController::delete' => '?',
            'App\\Controller\\CartController::deleteAll' => '?',
            'App\\Controller\\CartController::deletePanier' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::panierShow' => '?',
            'App\\Controller\\CartController::remove' => '?',
            'App\\Controller\\CartController::test' => '?',
            'App\\Controller\\CartController::update' => '?',
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\CategorieController::edit' => '?',
            'App\\Controller\\CategorieController::index' => '?',
            'App\\Controller\\CategorieController::new' => '?',
            'App\\Controller\\CategorieController::show' => '?',
            'App\\Controller\\ProduitController::AffichageBack' => '?',
            'App\\Controller\\ProduitController::AffichageFront' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:addPanier' => '?',
            'App\\Controller\\CartController:delete' => '?',
            'App\\Controller\\CartController:deleteAll' => '?',
            'App\\Controller\\CartController:deletePanier' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:panierShow' => '?',
            'App\\Controller\\CartController:remove' => '?',
            'App\\Controller\\CartController:test' => '?',
            'App\\Controller\\CartController:update' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\CategorieController:edit' => '?',
            'App\\Controller\\CategorieController:index' => '?',
            'App\\Controller\\CategorieController:new' => '?',
            'App\\Controller\\CategorieController:show' => '?',
            'App\\Controller\\ProduitController:AffichageBack' => '?',
            'App\\Controller\\ProduitController:AffichageFront' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
