<?php

namespace ContainerPmRUC0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8hRU1F1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8hRU1F1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8hRU1F1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PR' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService', true],
        ], [
            'PR' => 'App\\Repository\\PanierRepository',
        ]);
    }
}
