<?php

namespace ContainerPmRUC0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KQfLtfZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KQfLtfZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KQfLtfZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produit' => ['privates', '.errored..service_locator.KQfLtfZ.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.KQfLtfZ": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".'],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'produit' => 'App\\Entity\\Produit',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
