<?php

namespace ContainerPmRUC0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EJLorm2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EJLorm2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EJLorm2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LPR' => ['privates', 'App\\Repository\\LignePanierRepository', 'getLignePanierRepositoryService', true],
            'PR' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'LPR' => 'App\\Repository\\LignePanierRepository',
            'PR' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
