<?php

namespace ContainerXOESU7d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IgERDViService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.igERDVi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.igERDVi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.KQfLtfZ', 'get_ServiceLocator_KQfLtfZService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.KQfLtfZ', 'get_ServiceLocator_KQfLtfZService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.KQfLtfZ', 'get_ServiceLocator_KQfLtfZService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.KQfLtfZ', 'get_ServiceLocator_KQfLtfZService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
