<?php

namespace ContainerAkWKqhf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendrierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..b08g3n.App\Entity\Calendrier' shared service.
     *
     * @return \App\Entity\Calendrier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..b08g3n": it needs an instance of "App\\Entity\\Calendrier" but this type has been excluded in "config/services.yaml".');
    }
}
