<?php

namespace ContainerOsdRl3Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7_C5n1bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7.c5n1b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7.c5n1b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'SalleRe' => ['privates', 'App\\Repository\\SalleRepository', 'getSalleRepositoryService', true],
            'calendrierRepository' => ['privates', 'App\\Repository\\CalendrierRepository', 'getCalendrierRepositoryService', true],
        ], [
            'SalleRe' => 'App\\Repository\\SalleRepository',
            'calendrierRepository' => 'App\\Repository\\CalendrierRepository',
        ]);
    }
}
