<?php

namespace ContainerOsdRl3Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__FH8f7SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..fH8f7S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..fH8f7S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendrierRepository' => ['privates', 'App\\Repository\\CalendrierRepository', 'getCalendrierRepositoryService', true],
            'salle' => ['privates', '.errored..service_locator..fH8f7S.App\\Entity\\Salle', NULL, 'Cannot autowire service ".service_locator..fH8f7S": it needs an instance of "App\\Entity\\Salle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'calendrierRepository' => 'App\\Repository\\CalendrierRepository',
            'salle' => 'App\\Entity\\Salle',
        ]);
    }
}
