<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGx3VVsc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGx3VVsc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGx3VVsc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGx3VVsc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGx3VVsc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gx3VVsc',
    'container.build_id' => '840d2620',
    'container.build_time' => 1677978505,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGx3VVsc');
