<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOsdRl3Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsdRl3Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOsdRl3Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOsdRl3Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOsdRl3Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'OsdRl3Z',
    'container.build_id' => 'fee90176',
    'container.build_time' => 1677576331,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOsdRl3Z');
