<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEKKJBMY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEKKJBMY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEKKJBMY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEKKJBMY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEKKJBMY\App_KernelDevDebugContainer([
    'container.build_hash' => 'EKKJBMY',
    'container.build_id' => 'd2eb859a',
    'container.build_time' => 1676488813,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEKKJBMY');
